prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

ask {
    ex:factoryOrganization a hmas:Organization ;
                           hmas:hasResourceProfile ?x .
  
    ex:factoryBuilding a hmas:Workspace ;
                       hmas:contains ?x .
}
