prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

ask {
    bind (ex:factoryOrganization as ?org)

    ex:factoryBuilding a hmas:Workspace ;
                       hmas:contains ?x .
    ?org a hmas:Organization ;
         hmas:hasResourceProfile ?x .
}
