prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

select distinct ?org
where {
  ?org a hmas:Organization .
  
  ex:productionCell1 a hmas:Workspace ;
                     hmas:contains ?x .

  ?x hmas:isMaterialOf | hmas:isMemberOf ?org .
}
order by ?org
