prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

ask {
    bind (ex:factory as ?org)

    ex:productionCell1 a hmas:Workspace ;
                       hmas:contains ?x .
    ?org a hmas:Organization ;
         hmas:isSituatedOn ?x .
}