prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

ask {
    ex:factoryOrganization hmas:isSituatedOn ?x .
    ?workspace a hmas:Workspace ;
               hmas:contains ?x .

    filter (ex:productionCell1 = ?workspace ||
            ex:productionCell2 = ?workspace)
}

# How do we guarantee that the factory is situated on both production cells?