prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

ask {
    bind (ex:autonomousBob as ?ag1)
    bind (ex:factorySupervisor as ?ag2)
    
    ?ag1 hmas:isMemberOf ?org .
    ?ag2 hmas:isMemberOf ?org .
    ?org a hmas:Organization ;
         hmas:isSituatedOn ?ag1, ?ag2 .
}

# How to avoid duplicated variables
