prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

ask {
    bind (ex:ur5 as ?ag1)
    bind (ex:phantomX as ?ag2)
    
    ?ag1 hmas:isMaterialOf ?org .
    ?ag2 hmas:isMaterialOf ?org .
    ?org a hmas:Organization ;
         hmas:isSituatedOn ?ag1, ?ag2 .
}

# How to avoid duplicated variables