default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
- repo: local
  hooks:
  - id: model-test
    name: Profile check
    entry: python .acimov/model-test/precommit-test.py
    language: python
    files: \.ttl$
    stages: [commit, push, manual]
