prefix : <https://purl.org/hmas/>
prefix ex: <http://example.org/>
prefix sh: <http://www.w3.org/ns/shacl#> 

select ?actionExecutionSpec
where {
    ex:gripperMovable a :Signifier .
    ex:gripperMovable :signifies ?actionExecutionSpec .
    ?actionExecutionSpec a sh:NodeShape .
    ?actionExecutionSpec sh:class :ActionExecution .
}
order by ?actionExecutionSpec
