base <https://purl.org/hmas/interaction/>
prefix : <>
prefix hmas: <https://purl.org/hmas/core#>
prefix ex: <http://example.org/>

ask {
    bind (ex:gripperMovable as ?s)
    bind (ex:moveGripper as ?sp)
    ?s a hmas:Signifier .
    ?s :signifies ?sp .
}
