prefix : <https://purl.org/hmas/>
prefix ex: <http://example.org/>
prefix sh: <http://www.w3.org/ns/shacl#> 
prefix prov: <http://www.w3.org/ns/prov#>

select ?form
where {
	ex:moveGripperShape sh:property ?propertySpec .
	?propertySpec sh:path prov:used .
	{ 
		?propertySpec sh:hasValue ?form . 
	}  
	union
	{ 
		?propertySpec sh:or ?formShapeList . 
		?formShapeList rdf:rest*/rdf:first ?formShape . 
		?formShape sh:hasValue ?form .
	}  
}
order by ?form
