base <https://purl.org/hmas/interaction/>
prefix : <>
prefix hmas: <https://purl.org/hmas/core#>

ask {
    bind (ex:gripperJointSchema as ?sc)
    bind (ex:gripperJoint as ?i)
    ?i a :Input .
    ?i :hasSchema ?sc.
}
