base <https://purl.org/hmas/interaction>
prefix hmas: <https://purl.org/hmas/>

ask {
    bind (ex:gripperJointSchema as ?sc)
    bind (ex:gripperJoint as ?i)
    ?i a hmas:Input .
    ?i hmas:hasSchema ?sc.
}
