prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

ask {
    ex:SL_Logistics a ex:Logistics .
    ?orgModel a sh:NodeShape .
    ?orgModel rdfs:subClassOf hmas:Organization .
}
