prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?orgModel
where {
  ex:SL_Logistics a ?orgModel .
  ?orgModel a sh:NodeShape ;
            rdfs:subClassOf hmas:Organization .
}
order by ?orgModel
