prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?org
where {
  ex:SL_Logistics a ?orgModel ;
                  hmas:hasResourceProfile ?slOrgProfile .

  ?org a ?orgModel ;
       hmas:hasResourceProfile ?orgProfile .
  
  ?orgModel rdfs:subClassOf hmas:Organization .
  { ?orgModel a sh:NodeShape . }
  union
  { ?orgShape a sh:NodeShape ;
              sh:targetClass ?orgModel .
  }

  ?workspace hmas:contains ?slOrgProfile, ?orgProfile .

  filter(?org != ex:SL_Logistics)
}
order by ?org
