prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

ask {
    bind (ex:GL_Logistics as ?glOrg)

    ex:SL_Logistics a ?orgModel .
    ?orgModel a sh:NodeShape ;
              rdfs:subClassOf hmas:Organization .
    ?glOrg a ?orgModel .
    ?workspace hmas:contains ex:SL_Logistics, ?glOrg .
}