prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

ask {
    ?orgModel a sh:NodeShape ;
              rdfs:subClassOf hmas:Organization .
    ex:SL_Logistics a ?orgModel ;
                    hmas:hasResourceProfile ?slOrgProfile.
    ex:GL_Logistics a ?orgModel ;
                    hmas:hasResourceProfile ?glOrgProfile .
    ?workspace hmas:contains ?slOrgProfile, ?glOrgProfile .
  
}
