prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?orgValue
where {
  ex:SL_Logistics hmas:hasOrganizationalValue ?orgValue .
}
order by ?orgValue
