prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select distinct ?key ?val {
    ex:SL_Logistics a ?orgModel .
    
    {
	    ?orgModel a sh:NodeShape ;
		      rdfs:subClassOf hmas:Organization ;
		      sh:property [
		        sh:path hmas:hasOrganizationalValue ;
		        sh:qualifiedValueShape [
		          sh:class ?orgModelOrgValue
		        ]
		      ] .
        bind ("orgValue" as ?key)
        bind (?orgModelOrgValue as ?val)
    }
    union
    {
	    ?orgModel a sh:NodeShape ;
		      rdfs:subClassOf hmas:Organization ;
		      sh:property [
		        sh:path hmas:providesRole ;
		        sh:qualifiedValueShape [
		          sh:class ?orgModelRole
		        ]
		      ] .
        bind ("role" as ?key)
        bind (?orgModelRole as ?val)
    }
    union
    {
	    ?orgModel a sh:NodeShape ;
		      rdfs:subClassOf hmas:Organization ;
		      sh:property [
		        sh:path hmas:proposesMission ;
		        sh:qualifiedValueShape [
		          sh:class ?orgModelMission
		        ]
		      ] .
        bind ("mission" as ?key)
        bind (?orgModelMission as ?val)
    }
    union
    {
	    ?orgModel a sh:NodeShape ;
		      rdfs:subClassOf hmas:Organization ;
		      sh:property [
		        sh:path hmas:proposesFacility ;
		        sh:qualifiedValueShape [
		          sh:class ?orgModelFacility
		        ]
		      ] .
        bind ("facility" as ?key)
        bind (?orgModelFacility as ?val)
    }
}
order by ?key
