prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?facility
where {
  ex:SL_Logistics a ?orgModel .
  ?orgModel rdfs:subClassOf hmas:Organization ;
            sh:property [
              sh:path  hmas:proposesFacility ;
              sh:qualifiedValueShape [ sh:class ?facilityModel ] ;
            ] .
  { ?orgModel a sh:NodeShape . }
  union
  { ?orgShape a sh:NodeShape ;
              sh:targetClass ?orgModel .
  }

  ?facilityModel rdfs:subClassOf hmas:Facility .
  { ?facilityModel a sh:NodeShape . }
  union
  { ?facilityShape a sh:NodeShape ;
                   sh:targetClass ?facilityModel .
  }
  
  ?facilityModel a sh:NodeShape ;
                 rdfs:subClassOf hmas:Facility .
  
  ?facility a ?facilityModel
}
order by ?mission
