prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?group
where {
  ex:FL_Logistics a ?orgModel ;
                  hmas:isStructuredBy ?group .

  ?orgModel rdfs:subClassOf hmas:Organization .
  { ?orgModel a sh:NodeShape . }
  union
  { ?orgShape a sh:NodeShape ;
              sh:targetClass ?orgModel . }
}
order by ?group
