prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?groups
where {
  ex:FL_Logistics a ?orgModel ;
                  hmas:isStructuredBy ?groups .

  ?orgModel rdfs:subClassOf hmas:Organization .
  { ?orgModel a sh:NodeShape . }
  union
  { ?orgShape a sh:NodeShape ;
              sh:targetClass ?orgModel . }
  
  ?groups a ?groupModel ;
          hmas:isSubGroupOf ex:FL_AdministrativeDepartment .

  ?groupModel rdfs:subClassOf hmas:Group .
  { ?groupModel a sh:NodeShape . }
  union
  { ?groupShape a sh:NodeShape ;
                sh:targetClass ?groupModel . }
}
order by ?groups
