prefix hmas: <https://purl.org/hmas/>
prefix ex: <http://example.org/>

ask {
    bind (ex:platformSaintEtienne as ?platform)

    ex:agentSaintEtienne hmas:isHostedOn ?platform .

    ?platform a hmas:HypermediaMASPlatform .
}