prefix hmas: <https://purl.org/hmas/>
prefix ex: <http://example.org/>

ask {
    bind (ex:agentSaintEtienneProfile as ?profile)

    ex:agentSaintEtienne hmas:hasResourceProfile ?profile .
    ?profile a hmas:ResourceProfile .
}
