prefix hmas: <https://purl.org/hmas/>
prefix ex: <http://example.org/>

ask {
    bind (ex:platformSaintEtienneProfile as ?profile)

    ex:platformSaintEtienne hmas:hasResourceProfile ?profile .
    ?profile a hmas:ResourceProfile .
}
