prefix hmas: <https://purl.org/hmas/core#>
prefix ex: <http://example.org/>

ask {
    bind (ex:groundFloor as ?groundFloor)
    bind (ex:productionCell1 as ?cell1)
    bind (ex:productionCell2 as ?cell2)

    ex:factory hmas:contains ?groundFloor, ?cell1, ?cell2 .

    ?groundFloor a hmas:Workspace .
    ?cell1 a hmas:Workspace .
    ?cell2 a hmas:Workspace .
}