prefix hmas: <https://purl.org/hmas/>
prefix ex: <http://example.org/>

ask {
    bind (ex:factoryProfile as ?profile)

    ex:factory hmas:hasResourceProfile ?profile .
    ?profile a hmas:ResourceProfile .
}
