PREFIX : <#>

SELECT ?norm
WHERE {
  ?organization :enforcesNorm ?norm .
  ?norm :hasNormativeContext ?context .
  ?norm :prohibits ?prohibition .
  ?workspace :isPossiblyDescribedBy ?worldWithNorms .
  ?worldWithNorms :hasDeonticSpecification ?norm .
  ?workspace :isPossiblyDescribedBy ?context .
  ?workspace :isPossiblyDescribedBy ?prohibition .
  FILTER(?workspace = :myWorkspace && ?organization = :myOrganization)
}
