prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix hmas: <https://purl.org/hmas/>

ask {
  bind (ex:i3sLabWorkspace as ?workspace ) 
  bind (ex:i3sLab as ?organization)
  bind (ex:safetyRule as ?norm)
  ?organization hmas:enforcesNorm ?norm .
  ?norm hmas:hasNormativeContext ?context .
  ?norm hmas:allows ?allowed .
  ?allowed a hmas:Permission .
  ?workspace hmas:isPossiblyDescribedBy ?worldWithNorms .
  ?worldWithNorms hmas:hasDeonticSpecification ?norm .
  ?workspace hmas:isPossiblyDescribedBy ?context .
#  ?workspace hmas:isPossiblyDescribedBy ?allowed .
}


SELECT ?norm
WHERE {
  ?organization hmas:enforcesNorm ?norm .
  ?norm hmas:hasNormativeContext ?context .
  ?norm hmas:allows ?allowed .
  ?allowed a hmas:Permission .
  ?workspace hmas:isPossiblyDescribedBy ?worldWithNorms .
  ?worldWithNorms hmas:hasDeonticSpecification ?norm .
  ?workspace hmas:isPossiblyDescribedBy ?context .
#  ?workspace hmas:isPossiblyDescribedBy ?allowed .
  FILTER(?workspace = ex:i3sLabWorkspace &&  ?norm = ex:safetyRule && ?organization = ex:i3sLab)
}
