prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix hmas: <https://purl.org/hmas/>

# How to represent the negation in "ought not to be" ?

prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix hmas: <https://purl.org/hmas/>

ask {
  bind (ex:i3sLabWorkspace as ?workspace ) 
  bind (ex:i3sLab as ?organization)
  bind (ex:safetyRule as ?norm)
  ?organization hmas:enforcesRegulativeNorm ?norm .
  ?norm hmas:hasNormativeContext ?context .
  ?norm hmas:prohibits ?prohibition .
  ?prohibition a hmas:Prohibition .
  ?workspace hmas:isPossiblyDescribedBy ?worldWithNorms .
  ?worldWithNorms hmas:hasDeonticSpecification ?norm .
  ?workspace hmas:isPossiblyDescribedBy ?context .
#  ?workspace hmas:isPossiblyDescribedBy ?prohibition .
}


SELECT ?norm
WHERE {
  ?organization hmas:enforcesRegulativeNorm ?norm .
  ?norm hmas:hasNormativeContext ?context .
  ?norm hmas:prohibits ?prohibition .
  ?prohibition a hmas:Prohibition .
  ?workspace hmas:isPossiblyDescribedBy ?worldWithNorms .
  ?worldWithNorms hmas:hasDeonticSpecification ?norm .
  ?workspace hmas:isPossiblyDescribedBy ?context .
#  ?workspace hmas:isPossiblyDescribedBy ?prohibition .
  FILTER(?workspace = ex:i3sLabWorkspace &&  ?norm = ex:safetyRule && ?organization = ex:i3sLab)
}
