prefix ex: <http://example.org/>
prefix : <> .
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

SELECT ?role
WHERE {
  ?norm :hasNormativeTarget ?role .
}
