prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix hmas: <https://purl.org/hmas/>

ask {
  bind (ex:i3sLabWorkspace as ?workspace ) 
  bind (ex:i3sLab as ?organization)
  bind (ex:safetyRule as ?norm)
  ?norm a hmas:RegulativeNorm .
  ?workspace a hmas:Workspace .
  ?worldWithNorms a hmas:PossibleWorld .
  ?organization a hmas:Organization .
  ?organization hmas:enforcesRegulativeNorm ?norm .
  ?norm hmas:hasNormativeContext ?context .
  ?norm hmas:prohibits ?prohibition .
  ?prohibition a hmas:Prohibition .
  ?workspace hmas:isPossiblyDescribedBy ?worldWithNorms .
  ?worldWithNorms hmas:hasDeonticSpecification ?norm .
  ?workspace hmas:isPossiblyDescribedBy ?context .
  ?workspace hmas:isPossiblyDescribedBy ?prohibition .
}


#:door28 a :ClosedDoor .
#:door27 a :OpenDoor .
#:door12 a :Door .
#:WorldWithFire :definedBy ""ASK {?x a :Fire}""^^sparql:ask .
#GRAPH :WorldWithFire { [a :Fire] } .
#""FROM ?aWorld ASK {?x a :Fire}""^^sparql:ask => ?aWorld isPossiblyDescribed :WorldWithFire .
# 


#?workspace hmas:isPossiblyDescribedBy ?theDoorIsOpened .
#?workspace hmas:isPossiblyDescribedBy ?theDoorIsClosed .
#?workspace hmas:isPossiblyDescribedBy ?stateOfAffair3 .

#worldWithNorms R_context normativeContexWorld1 
#worldWithNorms R_ideal permissionWorld2
#worldWithNorms R_ideal permissionWorld3






# Cannot express this SPARQL query !
# Need to add the possible world semantics into behaviour class e.g. map the effects of this behaviour on the workspace's possible worlds.
# Thinking about a property :behavior :removesPossibleWorld :pastWorld .
# :behavior ::hasPrecondition :precondition .
# :Precondition rdf:subClassOf :PossibleWorld .
# :Postcondition rdf:subClassOf :PossibleWorld .
# :behavior :hasPostcondition :postcondition .

# :behavior :bringsItAboutThat :newPossibleWorldAdded .

# :behavior :canBeFullfilled xsd:boolean"true".
