prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

select distinct ?artifact
where {
  ex:FL_Logistics hmas:proposesSetting ?setting .

  ?artifact hmas:isMaterialOf ex:FL_Logistics .
  
  ?setting a ex:ReceivingSetting .
  
  ?usage a ?usageModel ;
         hmas:isUsageIn ?setting ;
         hmas:isUsageOf ?artifact .
}
order by ?artifact
