prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

select distinct ?artifact
where {
  ?access hmas:isAccessIn ex:ReceiveSetting ;
          hmas:isAccessFor ?facility ;
          hmas:isAccessTo ?artifact .

  ?artifact hmas:isMaterialOf ex:FL_Logistics ;
            hmas:hasFacility ?facility .
}
order by ?artifact
