prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

select distinct ?artifact
where {
  ?usage a ?usageModel ;
         hmas:isUsageIn ex:ReceivingSetting ;
         hmas:isUsageOf ?facility .

  ?artifact hmas:isMaterialOf ex:FL_Logistics ;
            hmas:hasFacility ?facility .
}
order by ?artifact
