prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

select distinct ?agent
where {
  ?usage a ?usageModel ;
         hmas:isUsageBy ?agent ;
         hmas:isUsageIn ex:PickingSetting .
}
order by ?agent
