prefix ex: <http://example.org/>
prefix hmas: <https://purl.org/hmas/>

select distinct ?agent
where {
  ?usage a ?usageModel ;
         hmas:isUsageIn ex:PickingSetting .

  ?use a hmas:Use ;
       hmas:isUseFor ?usage ;
       hmas:isUseBy ?agent .
}
order by ?agent
