prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?orgGoal
where {
  ex:Dept_Hiring sh:property ?pShape .

  ?pShape sh:path hmas:isMissionFor .

  {
    ?pShape sh:hasValue ?parentGoal .

    bind ( ?parentGoal as ?orgGoal )
  }
  union
  {
    ?pShape sh:hasValue ?parentGoal .

    ?subGoal hmas:isSubOrganizationalGoalOf ?parentGoal .

    bind ( ?subGoal as ?orgGoal )
  }
}
order by ?orgGoal
