prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?missionGoal
where {
  ex:Dept_Hiring sh:property [ sh:path hmas:isMissionFor ;
                               sh:hasValue ?orgGoal ;
                             ] .

  ?orgGoal hmas:hasSubOrganizationalGoal* ?missionGoal .
}
order by ?missionGoal
