prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select distinct ?orgGoal ?dependence ?orgGoalOther
where {
  ex:FL_Logistics hmas:proposesProcess ?process .

  ?process a ex:Hire_Process ;
           hmas:includesMission ?mission .

  ?mission hmas:includesOrganizationalGoal ?orgGoal .

  ?orgGoal ?dependence ?orgGoalOther .
  
  ?dependence rdfs:subPropertyOf hmas:isDependentOnOrganizationalGoal .  
}
order by ?orgGoal
