prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select distinct ?activity ?dependence ?activityOther
where {
  ex:FL_Logistics hmas:proposesActivityScheme ?activity .

  ?activity ?dependence ?activityOther .

  ?dependence rdfs:subPropertyOf hmas:isDependentOnActivityScheme .  
}
order by ?activity
