prefix ex: <http://example.org/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sh: <http://www.w3.org/ns/shacl#>
prefix hmas: <https://purl.org/hmas/>

select ?agent
where {
  ?mission a ?missionModel ;
    hmas:isMissionOf ?agent ;
    hmas:isMissionIn ex:FL_AccountManager_HiringProcess .
}
order by ?agent
