 base <https://purl.org/hmas/core>
 prefix : <#>

 ask {
     bind (<http://example.org/workspaces/manufacturing/artifacts/p1#s1> as ?s1)
     bind (<http://example.org/workspaces/manufacturing/artifacts/p1#leubot1> as ?a1)
     ?s1 a :Signifier .
     ?p1 a :ResourceProfile .
     ?a1 a :Artifact .
     ?s1 :isExposedIn ?p1 .
     ?p1 :isProfileOf ?a1 .
 }
