name: deploy
on:
  push:
    branches:
    - master
    - acimov-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.X'
        cache: 'pip'
    - run: pip install -r .acimov/requirements.txt && pip install pylode@git+https://github.com/HyperAgents/pyLODE@skos_tags
    - run: python .acimov/process_core.py
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -a
        path: public/
        remote_path: /var/www/hmas/html
        remote_host: ci.mines-stetienne.fr
        remote_user: hyperagents
        remote_key: ${{ secrets.SSH_PRIVATE }}
