name: fragments-check
on:
  push:
    branches:
    - test-workflow

jobs:
  fragments-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Launch model tests
      run: |
        pip install -r .acimov/profile_check/requirements.txt
        python .acimov/profile_check/complete-test.py --mode=actions --skip-pass --dev=${{ github.actor }}
    - name: Commit the report
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Github Actions"
        git add .acimov/profile_check/output/actions.ttl -f
        git commit -m "Provide automatic model test report"
        git remote set-url origin ${{ github.server_url }}/${{ github.repository }}
        git push