name: model-test
on:
  push:
    branches:
    - test-workflow


jobs:
  model-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Launch model tests
      run: |
        pip install -r .acimov/model-test/requirements.txt
        SUMMARY="$(python .acimov/model-test/complete-test.py --mode=actions --DEV_USERNAME=${{ github.actor }} --REPO_URI=${{ github.server_url }}/${{ github.repository }} --BRANCH=${{ github.ref_name }} --is-action)"

        TOKENS=($SUMMARY)
        echo "PASS=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
        echo "NOTTESTED=$(echo ${TOKENS[5]})" >> $GITHUB_ENV
        echo "CANNOTTELL=$(echo ${TOKENS[8]})" >> $GITHUB_ENV
        echo "MINORFAIL=$(echo ${TOKENS[11]})" >> $GITHUB_ENV
        echo "MAJORFAIL=$(echo ${TOKENS[14]})" >> $GITHUB_ENV

        REF=${{ github.ref }}
        echo "github.ref: $REF"
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
        echo $BRANCH_NAME
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
        echo "REPO=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Archive model test results
      uses: actions/upload-artifact@v3
      with:
        name: model-test-report
        path: .acimov/output/actions.md
    - name: Commit the report
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Github Actions"
        git add .acimov/output/actions.ttl .acimov/output/actions.md README.md -f
        git commit -m "Provide automatic model test report [skip actions]"
        git remote set-url origin ${{ github.server_url }}/${{ github.repository }}
        git push
    - name: Create the Pass Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: a242e427a25c90887a3213049eb60af7
        filename: ${{ env.REPO }}__${{ env.BRANCH }}.json
        label: MajorFail
        message: ${{ env.MAJORFAIL }}
        color: red