name: model-test
on:
  push:
    branches:
    - test-workflow

jobs:
  model-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        cache: 'pip'
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Launch model tests
      run: |
        pip install -r .acimov/model-test/requirements.txt
        python .acimov/model-test/complete-test.py \
          --mode=actions --skip-pass \
          --DEV_USERNAME=${{ github.actor }} \
          --REPO_URI={{ github.github.server_url }}/{{ github.repository }} \
          --BRANCH={{ github.ref_name }}
    - name: Commit the report
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "Github Actions"
        git add .acimov/output/actions.ttl .acimov/output/actions.md -f
        git commit -m "Provide automatic model test report"
        git remote set-url origin ${{ github.server_url }}/${{ github.repository }}
        git push